# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps: 

- script: |
      curl -O https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe            
      hyperexecute.exe -u $(LT_USERNAME) -k $(LT_ACCESS_KEY) -i yaml/win/pyunit_hyperexecute_autosplit_sample.yaml
      
  displayName: 'Run a hyperexecute job'
