# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'LT_USERNAME'
        required: true
        default: ''
      accesskey:
        description: 'LT_ACCESS_KEY'
        required: true
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Run HyperExecute Job
      run: |
        git clone https://github.com/vishnukdas/pyunit-selenium-hyperexecute-sample
        cd pyunit-selenium-hyperexecute-sample
        curl -O https://downloads.lambdatest.com/hyperexecute/linux/hyperexecute 
        chmod u+x hyperexecute
        ./hyperexecute --user '${{ github.event.inputs.username }}' --key '${{ github.event.inputs.accesskey }}' --config yaml/win/pyunit_hyperexecute_autosplit_sample.yaml

